---
- name: Create openvpn ovpn file directory
  file:
    path: "{{ openvpn_ovpn_dir }}"
    state: directory
    mode: 0755

- name: Copy openssl client extensions
  copy:
    src: openssl-client.ext
    dest: "{{ openvpn_key_dir }}"
    owner: root
    group: root
    mode: 0400

- name: Generate client key
  command: >-
    openssl req -nodes -newkey rsa:{{ openvpn_rsa_bits }} -keyout {{ item.1 }}.key -out {{ item.1 }}.csr
    -days 3650 -subj /CN=OpenVPN-Client-{{ inventory_hostname[:24] }}-{{ item.1[:24] }}/
  args:
    chdir: "{{ openvpn_key_dir }}"
    creates: "{{ item.1 }}.key"
  with_subelements:
    - "{{ clients }}"
    - client

- name: Protect client keys
  file:
    path: "{{ openvpn_key_dir }}/{{ item.1 }}.key"
    mode: 0400
  with_subelements:
    - "{{ clients }}"
    - client

- name: Sign client key
  command: openssl x509 -req -in {{ item.1 }}.csr -out {{ item.1 }}.crt -CA ca.crt -CAkey ca-key.pem -sha256 -days 3650 -extfile openssl-client.ext
  args:
    chdir: "{{ openvpn_key_dir }}"
    creates: "{{ item }}.crt"
  with_subelements:
    - "{{ clients }}"
    - client

- name: Register server ca key
  slurp:
    src: "{{ openvpn_key_dir }}/ca.crt"
  register: ca_cert

- name: Register tls-auth key
  slurp:
    src: "{{ openvpn_key_dir }}/ta.key"
  register: tls_auth

- name: Register client certs
  slurp:
    src: "{{ openvpn_key_dir }}/{{ item.1 }}.crt"
  with_subelements:
    - "{{ clients }}"
    - client
  register: client_certs

- name: Register client keys
  slurp:
    src: "{{ openvpn_key_dir }}/{{ item.1 }}.key"
  with_subelements:
    - "{{ clients }}"
    - client
  register: client_keys

- name: Generate client config
  no_log: "{{ openvpn_client_config_no_log }}"
  template:
    src: client.ovpn.j2
    dest: "{{ openvpn_ovpn_dir }}/{{ item.0.item.1 }}-{{ inventory_hostname }}.ovpn"
    owner: root
    group: root
    mode: 0400
  with_together:
    - "{{ client_certs.results }}"
    - "{{ client_keys.results }}"

- name: Fetch client config
  fetch:
    src: "{{ openvpn_ovpn_dir }}/{{ item.1 }}-{{ inventory_hostname }}.ovpn"
    dest: "{{ openvpn_fetch_client_configs_dir }}/{{ item.0.group }}/{{ item.1 }}-{{ openvpn_fetch_client_configs_suffix }}.ovpn"
    flat: true
  when: openvpn_fetch_client_configs
  with_subelements:
    - "{{ clients }}"
    - client
