---
- name: Check for firewalld
  ansible.builtin.command: which firewall-cmd
  register: firewalld
  check_mode: false
  changed_when: false  # Never report as changed
  failed_when: false

- name: Check for ufw
  ansible.builtin.command: which ufw
  register: ufw
  check_mode: false
  changed_when: false  # Never report as changed
  failed_when: false

- name: Check for iptables
  ansible.builtin.command: which iptables
  register: iptables
  check_mode: false
  changed_when: false  # Never report as changed
  failed_when: false

- name: Fail on both firewalld & ufw
  ansible.builtin.fail:
    msg: "Both FirewallD and UFW are detected, firewall situation is unknown"
  when: openvpn_firewall == 'auto' and firewalld.rc == 0 and ufw.rc == 0

- name: Installing iptables due to no firewall detected
  ansible.builtin.package:
    name: "{{ iptables_services_package_name }}"
    state: present
  register: iptables_installed
  when: firewalld.rc != 0 and ufw.rc != 0 and iptables.rc != 0
  notify: "Enable iptables"

- name: Add port rules (iptables)
  ansible.builtin.include_tasks: iptables.yml
  when: >-
    (openvpn_firewall == 'iptables')
    or
    (openvpn_firewall == 'auto' and firewalld.rc != 0 and ufw.rc != 0 and iptables.rc == 0)
    or
    (iptables_installed is defined)

- name: Add port rules (firewalld)
  ansible.builtin.include_tasks: firewalld.yml
  when: >-
    (openvpn_firewall == 'firewalld')
    or
    (openvpn_firewall == 'auto' and firewalld.rc == 0 and ufw.rc != 0)

- name: Add port rules (ufw)
  ansible.builtin.include_tasks: ufw.yml
  when: >-
    (openvpn_firewall == 'ufw')
    or
    (openvpn_firewall == 'auto' and firewalld.rc != 0 and ufw.rc == 0)
