---
- name: Check systemd existence as Docker Guest
  ansible.builtin.stat:
    path: /bin/systemctl
  when: ansible_virtualization_role is defined and ansible_virtualization_type == "docker" and ansible_virtualization_role == "guest"
  register: docker_stat_result

- name: Set systemd openvpn service name
  ansible.builtin.set_fact:
    openvpn_service_name: "openvpn@{{ openvpn_config_file }}.service"
  when: ansible_service_mgr == "systemd" or (docker_stat_result.stat is defined and docker_stat_result.stat.exists)

# Separate OpenVPN into client and server for CentOS/Rocky/RHEL
- name: Set service name for CentOS/Rocky/RHEL
  ansible.builtin.set_fact:
    openvpn_service_name: "openvpn-server@{{ openvpn_config_file }}.service"
  when:
    - ansible_distribution == "CentOS" or ansible_distribution == "Rocky" or ansible_distribution == "RedHat"
    - (ansible_distribution_version | int) >= 8

- name: Set OpenVPN base path for CentOS/Rocky/RHEL
  ansible.builtin.set_fact:
    openvpn_base_dir: "/etc/openvpn/server"
  when:
    - ansible_distribution == "CentOS" or ansible_distribution == "Rocky" or ansible_distribution == "RedHat"
    - (ansible_distribution_version | int) >= 8
