---
dependency:
  name: galaxy
  enabled: true
  options:
    role-file: molecule/shared/requirements.yml
    requirements-file: molecule/shared/collections.yml
driver:
  name: docker
lint: |
  ansible-lint
platforms:
  - name: centos8
    image: geerlingguy/docker-centos8-ansible 
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
    prepare: ../shared/prepare.yml
verifier:
  name: ansible
