---
- name: Restart openvpn
  ansible.builtin.service:
    name: "{{ openvpn_service_name }}"
    state: restarted
  # Github Actions doesn't allow entrypoints, so PID 1 isn't an init system
  when: ansible_service_mgr != "tail"

- name: Restart iptables
  ansible.builtin.service:
    name: iptables
    state: restarted

- name: Restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted

- name: Restart ufw
  ansible.builtin.service:
    name: ufw
    state: restarted

- name: Save iptables rules (Debian/Ubuntu and CentOS/RHEL/Fedora)
  ansible.builtin.shell:
    cmd: "{{ iptables_save_command }}"  # noqa command-instead-of-shell
  register: openvpn_iptables_save
  changed_when:
    - openvpn_iptables_save.rc == 0
  failed_when:
    - openvpn_iptables_save.rc != 0
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'
  listen: "save iptables"

- name: Build and install policy
  ansible.builtin.command: "{{ item }}"
  register: openvpn_install_policy
  changed_when:
    - openvpn_install_policy.rc == 0
  failed_when:
    - openvpn_install_policy.rc != 0
  args:
    chdir: /var/lib/selinux
  with_items:
    - "checkmodule -M -m -o {{ openvpn_selinux_module }}.mod {{ openvpn_selinux_module }}.te"
    - "semodule_package -o {{ openvpn_selinux_module }}.pp -m {{ openvpn_selinux_module }}.mod"
    - "semodule -i {{ openvpn_selinux_module }}.pp"
